[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cheap_lock = "E3TBZmfvWDuV6g4bAVR62bVoV9AJ3Y6utDKJsVEgxaLu"

[programs.devnet]
cheap_lock = "E3TBZmfvWDuV6g4bAVR62bVoV9AJ3Y6utDKJsVEgxaLu"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/cheap-lock"]
